***Week 1 assignment - Michael Ijeh***

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
#Question 1
np.__version__

'1.19.2'

In [3]:
#Question 2
pd.__version__

'1.1.3'

In [4]:
df_orig = pd.read_csv("datasets\car_prices.csv")
df_orig.head(7)

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   
5  BMW    1 Series  2012  premium unleaded (required)      230.0   
6  BMW    1 Series  2012  premium unleaded (required)      300.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   
5               6.0            MANUAL  rear wheel drive              2.0   
6               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   
5                     Luxury,Performance      Compact         Coupe   
6                     Luxury,Performance      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500  
5           28        18        3916  31200  
6           26        17        3916  44100

In [5]:
#Question 3
bmw_price = df_orig[df_orig['Make']=='BMW']
np.mean(bmw_price["MSRP"])

61546.76347305389

In [6]:
df_orig.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Make               11914 non-null  object 
 1   Model              11914 non-null  object 
 2   Year               11914 non-null  int64  
 3   Engine Fuel Type   11911 non-null  object 
 4   Engine HP          11845 non-null  float64
 5   Engine Cylinders   11884 non-null  float64
 6   Transmission Type  11914 non-null  object 
 7   Driven_Wheels      11914 non-null  object 
 8   Number of Doors    11908 non-null  float64
 9   Market Category    8172 non-null   object 
 10  Vehicle Size       11914 non-null  object 
 11  Vehicle Style      11914 non-null  object 
 12  highway MPG        11914 non-null  int64  
 13  city mpg           11914 non-null  int64  
 14  Popularity         11914 non-null  int64  
 15  MSRP               11914 non-null  int64  
dtypes: float64(3), int64(5

In [7]:
#Question 4
prices_2015 = df_orig[df_orig['Year']>=2015]
prices_2015['Engine HP'].isnull().sum()

51

In [9]:
mean_hp_before = np.mean(prices_2015['Engine HP'])
mean_hp_before

272.98771870794076

In [14]:
#Question 5
prices_2015['Engine HP'].fillna(value=mean_hp_before, inplace=True)
mean_hp_after = np.mean(prices_2015['Engine HP'])
mean_hp_after

272.98771870794116

In [38]:
#Initial attempt at Question 6
rr_orig =prices_2015[prices_2015['Make']=='Rolls-Royce']
rrs = rr_orig[["Engine HP", "Engine Cylinders", "highway MPG"]]
rrs.drop_duplicates()
print(rrs.info())
print(rrs['Engine HP'].unique())
print(rrs['Engine Cylinders'].unique())
print(rrs['highway MPG'].unique())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 15 entries, 3505 to 11450
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Engine HP         15 non-null     float64
 1   Engine Cylinders  15 non-null     float64
 2   highway MPG       15 non-null     int64  
dtypes: float64(2), int64(1)
memory usage: 480.0 bytes
None
[563. 453. 624.]
[12.]
[19 21]


In [39]:
#Second attempt at Question 6
rr_orig2 =df_orig[df_orig['Make']=='Rolls-Royce']
rrs2 = rr_orig2[["Engine HP", "Engine Cylinders", "highway MPG"]]
rrs2.drop_duplicates()
print(rrs2.info())
print(rrs2['Engine HP'].unique())
print(rrs2['Engine Cylinders'].unique())
print(rrs2['highway MPG'].unique())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 31 entries, 2921 to 11450
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Engine HP         31 non-null     float64
 1   Engine Cylinders  31 non-null     float64
 2   highway MPG       31 non-null     int64  
dtypes: float64(2), int64(1)
memory usage: 992.0 bytes
None
[325. 563. 322. 453. 624.]
[ 8. 12.]
[15 19 21 20]


In [59]:
#Given that there are 7 unique values from Engine HP and Engine Cylinders features, I used those two features to create the array
#However, I couldn't get a list to even transpose. Looks like x.T or even x.transpose() would not work for me.
#So I just took a guess on questions 6 and 7.
one = np.array(rrs2['Engine HP'].unique())
two = np.array(rrs2['Engine Cylinders'].unique())
x = []
x.append(one)
x.append(two)
print(x)


[array([325., 563., 322., 453., 624.]), array([ 8., 12.])]
